version: '2'

services:

  couchdb7:
    container_name: couchdb7
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=pass
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for guizhou map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "10984:5984"

  peer1.org4.guizhou.com: 
    container_name: peer1.org4.guizhou.com 
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb7:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pass
    depends_on:
      - couchdb7
    extends: 
      file:  base/docker-compose-base.yaml 
      service: peer1.org4.guizhou.com 
    extra_hosts: 
      - "orderer0.guizhou.com:192.168.70.153"
      - "orderer1.guizhou.com:192.168.70.154"
      - "orderer2.guizhou.com:192.168.70.155"
      - "orderer3.guizhou.com:192.168.70.156"
      - "orderer4.guizhou.com:192.168.70.157"
      - "orderer5.guizhou.com:192.168.70.158"
      - "peer0.org1.guizhou.com:192.168.70.153"
      - "peer0.org2.guizhou.com:192.168.70.154"
      - "peer0.org3.guizhou.com:192.168.70.155"
      - "peer0.org4.guizhou.com:192.168.70.156"
      - "peer0.org5.guizhou.com:192.168.70.157"
      - "peer0.org6.guizhou.com:192.168.70.158"
      - "peer1.org1.guizhou.com:192.168.70.153"
      - "peer1.org2.guizhou.com:192.168.70.154"
      - "peer1.org3.guizhou.com:192.168.70.155"
      - "peer1.org4.guizhou.com:192.168.70.156"
      - "peer1.org5.guizhou.com:192.168.70.157"
      - "peer1.org6.guizhou.com:192.168.70.158"
  
  # cli: 
  #   container_name: cli 
  #   image: 10.161.25.61:5000/hyperledger/fabric-tools 
  #   tty: true 
  #   environment: 
  #     - GOPATH=/opt/gopath 
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock 
  #     - CORE_LOGGING_LEVEL=DEBUG 
  #     - CORE_PEER_ID=cli 
  #     - CORE_PEER_ADDRESS=peer0.org2.guizhou.com:7051 
  #     - CORE_PEER_LOCALMSPID=Org2MSP 
  #     - CORE_PEER_LOCALMSPTYPE=bccsp
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.guizhou.com/peers/peer0.org2.guizhou.com/tls/server.crt 
  #     - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.guizhou.com/peers/peer0.org2.guizhou.com/tls/server.key 
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.guizhou.com/peers/peer0.org2.guizhou.com/tls/ca.crt 
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.guizhou.com/users/Admin@org2.guizhou.com/msp 
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer 
  #   volumes: 
  #       - /var/run/:/host/var/run/ 
  #       - ../chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/guizhous/chaincode/go 
  #       - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ 
  #       - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/ 
  #       - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts 
  #   depends_on: 
  #     - peer0.org2.guizhou.com 
  #   extra_hosts: 
  #    - "orderer0.guizhou.com:10.161.25.62" 
  #    - "orderer1.guizhou.com:10.161.25.63" 
  #    - "orderer2.guizhou.com:10.161.25.64" 
  #    - "peer0.org1.guizhou.com:10.161.25.62"
  #    - "peer0.org2.guizhou.com:10.161.25.63"
  #    - "peer1.org1.guizhou.com:10.161.25.64"
  #    - "peer1.org2.guizhou.com:10.161.25.65" 

