version: '2'
services:
        zookeeper0:
                container_name: zookeeper0
                hostname: zookeeper0.guizhou.com
                image: hyperledger/fabric-zookeeper:amd64-0.4.10
                restart: always
                environment:
                        - ZOO_MY_ID=1
                        - ZOO_SERVERS=server.1=zookeeper0.guizhou.com:2888:3888 server.2=zookeeper1.guizhou.com:2888:3888 server.3=zookeeper2.guizhou.com:2888:3888
                        - quorumListenOnAllIPs=true
                ports:
                        - "2181:2181"
                        - "2888:2888"
                        - "3888:3888"
                extra_hosts:
                        - "zookeeper0.guizhou.com:47.94.241.242"
                        - "zookeeper1.guizhou.com:60.205.213.254"
                        - "zookeeper2.guizhou.com:140.143.236.52"
