# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
### Send POST request with json body
POST http://127.0.0.1:8080/fabric/chaincode/queryChaincode
Content-Type: application/json

{
  "channelName":"mychannel",
  "chaincodeName":"mycc",
  "func":"query",
  "args":["a"]
}

###
POST http://127.0.0.1:8080/fabric/chaincode/queryUserModel
Content-Type: application/json

{
  "name":"aa",
  "id":"a"
}

###
POST http://127.0.0.1:8080/fabric/chaincode/invokeVerification
Content-Type: application/json

{
  "id":"987654321123456588",
  "date":"2018-03-30",
  "userDataJson":"{\"UserInfo\":{\"ID\":\"987654321123456588\",\"Name\":\"zhangsan\"},\"Date\":\"2018-03-30\",\"UserDataList\":[{\"DataSrc\":\"03\",\"DataList\":[{\"DataId\":\"01\",\"Result\":\"0\",\"Message\":\"has been alive\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"\",\"Result\":\"\",\"Message\":\"\",\"DateTime\":\"\"}]},{\"DataSrc\":\"02\",\"DataList\":[{\"DataId\":\"02\",\"Result\":\"1\",\"Message\":\"treated at outpatient service\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"03\",\"Result\":\"1\",\"Message\":\"purchase drug\",\"DateTime\":\"2018-02-30\"}]}]}"
}

###
POST http://127.0.0.1:8080/fabric/chaincode/invokeVerification
Content-Type: application/json

{
"id":"987654321123456588",
"date":"2018-03-30",
"userDataJson":"{\"UserInfo\":{\"ID\":\"110101819181283850\",\"Name\":\"老王\"},\"Date\":\"2018-03-30\",\"UserDataList\":[{\"DataSrc\":\"03\",\"DataList\":[{\"DataId\":\"01\",\"Result\":\"0\",\"Message\":\"has been alive\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"\",\"Result\":\"\",\"Message\":\"\",\"DateTime\":\"\"}]},{\"DataSrc\":\"02\",\"DataList\":[{\"DataId\":\"02\",\"Result\":\"1\",\"Message\":\"treated at outpatient service\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"03\",\"Result\":\"1\",\"Message\":\"purchase drug\",\"DateTime\":\"2018-02-30\"}]}]}"
}

###
POST http://47.104.188.61:8080/fabric/chaincode/invokeVerification
Content-Type: application/json

{
  "id":"987654321123456588",
  "date":"2018-03-30",
  "userDataJson":"{\"UserInfo\":{\"ID\":\"110101819181283850\",\"Name\":\"老王\"},\"Date\":\"2018-03-30\",\"UserDataList\":[{\"DataSrc\":\"03\",\"DataList\":[{\"DataId\":\"01\",\"Result\":\"0\",\"Message\":\"has been alive\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"\",\"Result\":\"\",\"Message\":\"\",\"DateTime\":\"\"}]},{\"DataSrc\":\"02\",\"DataList\":[{\"DataId\":\"02\",\"Result\":\"1\",\"Message\":\"treated at outpatient service\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"03\",\"Result\":\"1\",\"Message\":\"purchase drug\",\"DateTime\":\"2018-02-30\"}]}]}"
}

###
POST http://47.104.188.61:8080/fabric/chaincode/invokeVerification
Content-Type: application/json

{
  "id":"987654321123456588",
  "date":"2018-03-30",
  "userDataJson":"{\"UserInfo\":{\"ID\":\"987654321123456588\",\"Name\":\"zhangsan\"},\"Date\":\"2018-03-30\",\"UserDataList\":[{\"DataSrc\":\"03\",\"DataList\":[{\"DataId\":\"01\",\"Result\":\"0\",\"Message\":\"has been alive\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"\",\"Result\":\"\",\"Message\":\"\",\"DateTime\":\"\"}]},{\"DataSrc\":\"02\",\"DataList\":[{\"DataId\":\"02\",\"Result\":\"1\",\"Message\":\"treated at outpatient service\",\"DateTime\":\"2018-09-30\"},{\"DataId\":\"03\",\"Result\":\"1\",\"Message\":\"purchase drug\",\"DateTime\":\"2018-02-30\"}]}]}"
}

###
POST http://127.0.0.1:8080/yanglao/api/fetchUserInfo
Content-Type: application/json

{
  "location":"522526",
  "date":"201811",
  "pageStart":1,
  "pageSize":100
}

###
POST http://127.0.0.1:8080/yanglao/api/fakeFetchUserInfoList
Content-Type: application/json

{
  "location":"522526",
  "date":"201811",
  "pageStart":1,
  "pageSize":100
}

###
POST http://127.0.0.1:8080/yanglao/api/getUserStatusData
Content-Type: application/json

{
  "location":"5202",
  "date":"201811",
  "pageStart":1,
  "pageSize":100
}

###

POST http://127.0.0.1:8080/yanglao/api/fetchUserInfo
Content-Type: application/x-www-form-urlencoded

location=522526&date=201811

###
POST http://127.0.0.1:8080/yanglao/api/fetchUserData
Content-Type: application/json

{
  "UserInfo":{
    "ID":"522526195510024000",
    "Name":"李朝光"
  },
  "Date":"201811",
  "TargetDataList":[
    {
      "DataSrc":"02",
      "DataList":[
        {"DataId":"01"},
        {"DataId":"02"},
        {"DataId":"03"}
      ]
    },
    {
      "DataSrc":"03",
      "DataList":[
        {"DataId":"01"}
      ]
    },
    {
      "DataSrc":"04",
      "DataList":[
        {"DataId":"01"},
        {"DataId":"02"},
        {"DataId":"03"},
        {"DataId":"04"}
      ]
    }
  ]
}

###