# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  peer0.org1.guizhou.com:
    container_name: peer0.org1.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.guizhou.com
      - CORE_PEER_ADDRESS=peer0.org1.guizhou.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.guizhou.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.guizhou.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org1.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.guizhou.com/peers/peer0.org1.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.guizhou.com/peers/peer0.org1.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org1.guizhou.com:
    container_name: peer1.org1.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.guizhou.com
      - CORE_PEER_ADDRESS=peer1.org1.guizhou.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.guizhou.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.guizhou.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.org1.guizhou.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.guizhou.com/peers/peer1.org1.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.guizhou.com/peers/peer1.org1.guizhou.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053

  peer0.org2.guizhou.com:
    container_name: peer0.org2.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.guizhou.com
      - CORE_PEER_ADDRESS=peer0.org2.guizhou.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.guizhou.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.guizhou.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org2.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.guizhou.com/peers/peer0.org2.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.guizhou.com/peers/peer0.org2.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org2.guizhou.com:
    container_name: peer1.org2.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.guizhou.com
      - CORE_PEER_ADDRESS=peer1.org2.guizhou.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org2.guizhou.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.guizhou.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.org2.guizhou.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.guizhou.com/peers/peer1.org2.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.guizhou.com/peers/peer1.org2.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053

  peer0.org3.guizhou.com:
    container_name: peer0.org3.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org3.guizhou.com
      - CORE_PEER_ADDRESS=peer0.org3.guizhou.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.guizhou.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.guizhou.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org3.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.guizhou.com/peers/peer0.org3.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.guizhou.com/peers/peer0.org3.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org3.guizhou.com:
    container_name: peer1.org3.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org3.guizhou.com
      - CORE_PEER_ADDRESS=peer1.org3.guizhou.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org3.guizhou.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.guizhou.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.org3.guizhou.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org3.guizhou.com/peers/peer1.org3.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org3.guizhou.com/peers/peer1.org3.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053

  peer0.org4.guizhou.com:
    container_name: peer0.org4.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org4.guizhou.com
      - CORE_PEER_ADDRESS=peer0.org4.guizhou.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org4.guizhou.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.guizhou.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org4.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org4.guizhou.com/peers/peer0.org4.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org4.guizhou.com/peers/peer0.org4.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org4.guizhou.com:
    container_name: peer1.org4.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org4.guizhou.com
      - CORE_PEER_ADDRESS=peer1.org4.guizhou.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org4.guizhou.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org4.guizhou.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.org4.guizhou.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org4.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org4.guizhou.com/peers/peer1.org4.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org4.guizhou.com/peers/peer1.org4.guizhou.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053

  peer0.org5.guizhou.com:
    container_name: peer0.org5.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org5.guizhou.com
      - CORE_PEER_ADDRESS=peer0.org5.guizhou.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org5.guizhou.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.guizhou.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org5.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org5MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org5.guizhou.com/peers/peer0.org5.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org5.guizhou.com/peers/peer0.org5.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org5.guizhou.com:
    container_name: peer1.org5.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org5.guizhou.com
      - CORE_PEER_ADDRESS=peer1.org5.guizhou.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org5.guizhou.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org5.guizhou.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.org5.guizhou.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org5.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org5MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org5.guizhou.com/peers/peer1.org5.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org5.guizhou.com/peers/peer1.org5.guizhou.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053

  peer0.org6.guizhou.com:
    container_name: peer0.org6.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org6.guizhou.com
      - CORE_PEER_ADDRESS=peer0.org6.guizhou.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org6.guizhou.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org6.guizhou.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.org6.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org6MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org6.guizhou.com/peers/peer0.org6.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org6.guizhou.com/peers/peer0.org6.guizhou.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org6.guizhou.com:
    container_name: peer1.org6.guizhou.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org6.guizhou.com
      - CORE_PEER_ADDRESS=peer1.org6.guizhou.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org6.guizhou.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org6.guizhou.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peer1.org6.guizhou.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org6.guizhou.com:7051
      - CORE_PEER_LOCALMSPID=Org6MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org6.guizhou.com/peers/peer1.org6.guizhou.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org6.guizhou.com/peers/peer1.org6.guizhou.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:8051
      - 8052:8052
      - 8053:8053

