version: '2'
services:
        zookeeper2:
                container_name: zookeeper2
                hostname: zookeeper2.guizhou.com
                image: hyperledger/fabric-zookeeper:amd64-0.4.10
                restart: always
                environment:
                        - ZOO_MY_ID=3
                        - ZOO_SERVERS=server.1=zookeeper0.guizhou.com:2888:3888 server.2=zookeeper1.guizhou.com:2888:3888 server.3=zookeeper2.guizhou.com:2888:3888
                        - quorumListenOnAllIPs=true
                ports:
                        - "2181:2181"
                        - "2888:2888"
                        - "3888:3888"
                extra_hosts:
                        - "zookeeper0.guizhou.com:192.168.70.153"
                        - "zookeeper1.guizhou.com:192.168.70.154"
                        - "zookeeper2.guizhou.com:192.168.70.155"
                        - "kafka0.guizhou.com:192.168.70.153"
                        - "kafka1.guizhou.com:192.168.70.153"
                        - "kafka2.guizhou.com:192.168.70.154"
                        - "kafka3.guizhou.com:192.168.70.155"
                        - "kafka4.guizhou.com:192.168.70.156"
                        - "kafka5.guizhou.com:192.168.70.157"
                        - "kafka6.guizhou.com:192.168.70.158"
