# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.guizhou.com:
    container_name: orderer0.guizhou.com
    image: hyperledger/fabric-orderer:1.2.0
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=e2e_default
      # - ORDERER_GENERAL_LOGLEVEL=error
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      #- ORDERER_GENERAL_GENESISPROFILE=guizhouOrdererGenesis
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      #- ORDERER_GENERAL_LEDGERTYPE=ram
      #- ORDERER_GENERAL_LEDGERTYPE=file
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      - ORDERER_KAFKA_RETRY_LONGINTERVAL=10s 
      - ORDERER_KAFKA_RETRY_LONGTOTAL=100s 
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_KAFKA_BROKERS=[kafka0.guizhou.com:9092,kafka1.guizhou.com:10092,kafka2.guizhou.com:9092,kafka3.guizhou.com:9092,kafka4.guizhou.com:9092,kafka5.guizhou.com:9092,kafka6.guizhou.com:9092]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/guizhou.com/orderers/orderer0.guizhou.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/guizhou.com/orderers/orderer0.guizhou.com/tls/:/var/hyperledger/orderer/tls
    networks:
      default:
        aliases:
          - e2e
    ports:
      - 7050:7050
    extra_hosts:
     - "kafka0.guizhou.com:192.168.70.153"
     - "kafka1.guizhou.com:192.168.70.153"
     - "kafka2.guizhou.com:192.168.70.154"
     - "kafka3.guizhou.com:192.168.70.155"
     - "kafka4.guizhou.com:192.168.70.156"
     - "kafka5.guizhou.com:192.168.70.157"
     - "kafka6.guizhou.com:192.168.70.158"

