version: '2'

services:
        kafka2:
                container_name: kafka2
                hostname: kafka2.guizhou.com
                image: hyperledger/fabric-kafka:amd64-0.4.10
                restart: always
                environment:
                        - KAFKA_BROKER_ID=2
                        - KAFKA_MIN_INSYNC_REPLICAS=2
                        - KAFKA_DEFAULT_REPLICATION_FACTOR=3
                        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.guizhou.com:2181,zookeeper1.guizhou.com:2181,zookeeper2.guizhou.com:2181
                        - KAFKA_MESSAGE_MAX_BYTES=103809024
                        - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
                        - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
                        - KAFKA_LOG_RETENTION_MS=-1
                       # - KAFKA_ADVERTISED_HOST_NAME=172.17.128.37
                ports:
                        - "9092:9092"
                extra_hosts:
                        - "zookeeper0.guizhou.com:192.168.70.153"
                        - "zookeeper1.guizhou.com:192.168.70.154"
                        - "zookeeper2.guizhou.com:192.168.70.155"
                        - "kafka0.guizhou.com:192.168.70.153"
                        - "kafka1.guizhou.com:192.168.70.153"
                        - "kafka2.guizhou.com:192.168.70.154"
                        - "kafka3.guizhou.com:192.168.70.155"
                        - "kafka4.guizhou.com:192.168.70.156"
                        - "kafka5.guizhou.com:192.168.70.157"
                        - "kafka6.guizhou.com:192.168.70.158"
